# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/alvise/3DComplete-Project-by-ARMA

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/alvise/3DComplete-Project-by-ARMA

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running interactive CMake command-line interface..."
	/usr/bin/cmake -i .
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alvise/3DComplete-Project-by-ARMA/CMakeFiles /home/alvise/3DComplete-Project-by-ARMA/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/alvise/3DComplete-Project-by-ARMA/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named coplanarity

# Build rule for target.
coplanarity: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 coplanarity
.PHONY : coplanarity

# fast build rule for target.
coplanarity/fast:
	$(MAKE) -f CMakeFiles/coplanarity.dir/build.make CMakeFiles/coplanarity.dir/build
.PHONY : coplanarity/fast

#=============================================================================
# Target rules for targets named progetto

# Build rule for target.
progetto: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 progetto
.PHONY : progetto

# fast build rule for target.
progetto/fast:
	$(MAKE) -f CMakeFiles/progetto.dir/build.make CMakeFiles/progetto.dir/build
.PHONY : progetto/fast

src/codice_progetto.o: src/codice_progetto.cpp.o
.PHONY : src/codice_progetto.o

# target to build an object file
src/codice_progetto.cpp.o:
	$(MAKE) -f CMakeFiles/progetto.dir/build.make CMakeFiles/progetto.dir/src/codice_progetto.cpp.o
.PHONY : src/codice_progetto.cpp.o

src/codice_progetto.i: src/codice_progetto.cpp.i
.PHONY : src/codice_progetto.i

# target to preprocess a source file
src/codice_progetto.cpp.i:
	$(MAKE) -f CMakeFiles/progetto.dir/build.make CMakeFiles/progetto.dir/src/codice_progetto.cpp.i
.PHONY : src/codice_progetto.cpp.i

src/codice_progetto.s: src/codice_progetto.cpp.s
.PHONY : src/codice_progetto.s

# target to generate assembly for a file
src/codice_progetto.cpp.s:
	$(MAKE) -f CMakeFiles/progetto.dir/build.make CMakeFiles/progetto.dir/src/codice_progetto.cpp.s
.PHONY : src/codice_progetto.cpp.s

src/coplanarity.o: src/coplanarity.cpp.o
.PHONY : src/coplanarity.o

# target to build an object file
src/coplanarity.cpp.o:
	$(MAKE) -f CMakeFiles/coplanarity.dir/build.make CMakeFiles/coplanarity.dir/src/coplanarity.cpp.o
.PHONY : src/coplanarity.cpp.o

src/coplanarity.i: src/coplanarity.cpp.i
.PHONY : src/coplanarity.i

# target to preprocess a source file
src/coplanarity.cpp.i:
	$(MAKE) -f CMakeFiles/coplanarity.dir/build.make CMakeFiles/coplanarity.dir/src/coplanarity.cpp.i
.PHONY : src/coplanarity.cpp.i

src/coplanarity.s: src/coplanarity.cpp.s
.PHONY : src/coplanarity.s

# target to generate assembly for a file
src/coplanarity.cpp.s:
	$(MAKE) -f CMakeFiles/coplanarity.dir/build.make CMakeFiles/coplanarity.dir/src/coplanarity.cpp.s
.PHONY : src/coplanarity.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... coplanarity"
	@echo "... edit_cache"
	@echo "... progetto"
	@echo "... rebuild_cache"
	@echo "... src/codice_progetto.o"
	@echo "... src/codice_progetto.i"
	@echo "... src/codice_progetto.s"
	@echo "... src/coplanarity.o"
	@echo "... src/coplanarity.i"
	@echo "... src/coplanarity.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

